console.log("Waheed");
let a = "Waheed";
console.log(a);
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[3]);
console.log(a[4]);
console.log(a[5]);
console.log(a.length);
let realName = "Faheem";
let freind = "Jamshiad";
console.log("His name " + realName + " and his freinds name " + freind);
console.log(`His name is ${realName} and his freind name is ${freind}`);
let b = "Waseem";
console.log(b.toUpperCase());
console.log(b.toLowerCase());
console.log(b.slice(1,5));
console.log(b.slice(1));
console.log(b.replace("Wa", "59"));
console.log(b.concat(a, "Faheem", "Naveed", "Umar"));